// 从 .env 或系统环境变量读取配置，生成 src/core/config.js
const fs = require('fs')
const path = require('path')

// 尝试从 .env 文件加载（本地开发用）
function loadEnvFile() {
    const envPath = path.join(__dirname, '..', '.env')
    if (fs.existsSync(envPath)) {
        const content = fs.readFileSync(envPath, 'utf8')
        content.split('\n').forEach(line => {
            const trimmed = line.trim()
            if (!trimmed || trimmed.startsWith('#')) return
            const eqIdx = trimmed.indexOf('=')
            if (eqIdx > 0) {
                const key = trimmed.substring(0, eqIdx).trim()
                const value = trimmed.substring(eqIdx + 1).trim()
                if (!process.env[key]) process.env[key] = value
            }
        })
    }
}
loadEnvFile()

const SUPABASE_URL = process.env.SUPABASE_URL
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY
const SUPABASE_STORAGE_URL = process.env.SUPABASE_STORAGE_URL || ''
const PEPPER = process.env.PEPPER || ''
const USER_EMAILS_LAODA = process.env.USER_EMAILS_LAODA || ''
const USER_EMAILS_XIAODI = process.env.USER_EMAILS_XIAODI || ''
const DEBUG = process.env.DEBUG || 'false'

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
    console.error('错误：缺少环境变量 SUPABASE_URL 和 SUPABASE_ANON_KEY')
    console.error('请复制 .env.example 为 .env 并填入实际值')
    process.exit(1)
}

const lines = [
    `window.__APP_CONFIG__ = {`,
    `    SUPABASE_URL: ${JSON.stringify(SUPABASE_URL)},`,
    `    SUPABASE_ANON_KEY: ${JSON.stringify(SUPABASE_ANON_KEY)},`,
]

if (SUPABASE_STORAGE_URL) {
    lines.push(`    SUPABASE_STORAGE_URL: ${JSON.stringify(SUPABASE_STORAGE_URL)},`)
}

if (PEPPER) {
    lines.push(`    PEPPER: ${JSON.stringify(PEPPER)},`)
}

if (USER_EMAILS_LAODA && USER_EMAILS_XIAODI) {
    lines.push(`    USER_EMAILS: {`)
    lines.push(`        laoda: ${JSON.stringify(USER_EMAILS_LAODA)},`)
    lines.push(`        xiaodi: ${JSON.stringify(USER_EMAILS_XIAODI)}`)
    lines.push(`    }`)
}

if (DEBUG === 'true') {
    lines.push(`    DEBUG: true`)
}

lines.push(`}`)

const header = '// Auto-generated by scripts/build-config.js — DO NOT EDIT\n'
const content = header + lines.join('\n') + '\n'

// Write to project root (where index.html loads from)
const rootConfigPath = path.join(__dirname, '..', 'config.js')
fs.writeFileSync(rootConfigPath, content, 'utf8')
console.log('config.js 已生成')

// Also write to src/core/ for future ES module usage
const coreDir = path.join(__dirname, '..', 'src', 'core')
if (!fs.existsSync(coreDir)) fs.mkdirSync(coreDir, { recursive: true })
const coreConfigPath = path.join(coreDir, 'config.js')
fs.writeFileSync(coreConfigPath, content, 'utf8')
console.log('src/core/config.js 已生成')

// Auto-bump version numbers in HTML for cache busting
const BUILD_VERSION = Date.now().toString(36)
const htmlFiles = ['index.html', 'index-mobile.html']
htmlFiles.forEach(file => {
    const htmlPath = path.join(__dirname, '..', file)
    if (!fs.existsSync(htmlPath)) return
    let html = fs.readFileSync(htmlPath, 'utf8')
    html = html.replace(/(app\.js\?v=)\w+/g, '$1' + BUILD_VERSION)
    html = html.replace(/(mobile-app\.js\?v=)\w+/g, '$1' + BUILD_VERSION)
    html = html.replace(/(common\.js\?v=)\w+/g, '$1' + BUILD_VERSION)
    fs.writeFileSync(htmlPath, html, 'utf8')
    console.log(`${file} 版本号已更新 → ${BUILD_VERSION}`)
})
